name: Build and push docker image

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      registry_name:
        required: true
        type: string
      release_created:
        required: true
        type: boolean
      version_tag:
        required: false
        type: string
      dockerfile_path:
        required: false
        type: string
        default: "./Dockerfile"
      dockerfile_context_path:
        required: false
        type: string
        default: "."
    outputs:
      image_tag:
        description: "Either the short SHA if release_created is false or version_tag"
        value: ${{ jobs.buildAndPushDockerImage.steps.image_tag.outputs.value }}
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  buildAndPushDockerImage:
    name: "Build and Push"
    runs-on: ubuntu-20.04

    steps:
      - run: echo "release_created ${{ inputs.release_created }}"
      - run: echo "version_tag ${{ inputs.version_tag }}"
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate a short SHA
        id: short_sha
        run: echo "::set-output name=value::$(git rev-parse --short ${{ github.sha }})"

      - name: "Generate the image tag"
        id: image_tag
        run: echo "::set-output name=value::${{ inputs.release_created && inputs.version_tag || steps.short_sha.outputs.value }}"

      - name: Configure docker
        run: echo ${{ secrets.registry_password }} | docker login ${{ inputs.registry_name }} --username ${{ secrets.registry_username }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          docker build --file ${{ inputs.dockerfile_path }} --tag ${{ inputs.repository_name }} ${{ inputs.dockerfile_context_path }}

      - name: Tag image with version_tag if given
        run: |
          docker tag ${{ inputs.repository_name }} ${{ inputs.registry_name }}/${{ inputs.repository_name }}:${{ steps.image_tag.outputs.value }}

      - name: Push image
        run: |
          docker push ${{ inputs.registry_name }}/${{ inputs.repository_name }} --all-tags
